# Generated by Django 5.1.1 on 2024-10-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appointment_id_alter_loyaltypoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
